#file: noinspection SpringBootApplicationYaml
spring:
  application:
    name: catalog
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres-db:5432/eCommerce
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    properties:
      hibernate:
        default_schema: catalog_schema
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql


server:
  port: 8086

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
