server:
  port: 8081

spring:
  application:
    name: catalog
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres-db:5432/eCommerce
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    properties:
      hibernate:
        default_schema: catalog_schema
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql


spring.cloud.stream:
  defaultBinder: rabbit
  default.contentType: application/json
  bindings.price-out-0:
    destination: price

spring.cloud.stream.bindings.consumeMessage-in-0.consumer:
  maxAttempts: 3
  backOffInitialInterval: 500
  backOffMaxInterval: 1000
  backOffMultiplier: 2.0

spring.cloud.stream.rabbit.bindings.consumeMessage-in-0.consumer:
  autoBindDlq: true
  republishToDlq: true

spring.rabbitmq:
  host: ${MESSAGE_HOST:localhost}
  port: 5672
  username: guest
  password: guest

---

spring.config.activate.on-profile: docker

server:
  port: 8080

spring:
  application:
    name: catalog
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres-db:5432/eCommerce
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    properties:
      hibernate:
        default_schema: catalog_schema
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql


spring.rabbitmq:
  host: message
