server:
  port: 8080

spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes:
        - id: eureka-web-start
          uri: http://eureka-server:8761
          predicates:
            - Path=/eureka/web
          filters:
            - SetPath=/

        - id: eureka-web-other
          uri: http://eureka-server:8761
          predicates:
            - Path=/eureka/**

        - id: catalog
          uri: lb://catalog
          predicates:
            - Path=/catalog/**

        - id: inventory
          uri: lb://inventory
          predicates:
            - Path=/inventory/**

        - id: price
          uri: lb://price
          predicates:
            - Path=/price/**

eureka:
  instance:
    hostname: gateway
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 30
  client:
    service-url:
      defaultZone: http://eureka-server:8761/ # Alterado aqui
    register-with-eureka: true
    fetch-registry: true


spring.cloud.stream:
  defaultBinder: rabbit
  default.contentType: application/json
  bindings.price-out-0:
    destination: price

spring.cloud.stream.bindings.consumeMessage-in-0.consumer:
  maxAttempts: 3
  backOffInitialInterval: 500
  backOffMaxInterval: 1000
  backOffMultiplier: 2.0

spring.cloud.stream.rabbit.bindings.consumeMessage-in-0.consumer:
  autoBindDlq: true
  republishToDlq: true
  
  
spring.rabbitmq:
  host: ${MESSAGE_HOST:localhost}
  port: 5672
  username: guest
  password: guest

---
spring.config.activate.on-profile: docker

spring.rabbitmq:
  host: message