fullnameOverride: catalog

image:
  name: catalog

ports:
  - containerPort: 8080

env:
  SPRING_PROFILES_ACTIVE: "docker"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres-db:5432/eCommerce"
  SPRING_DATASOURCE_USERNAME: "postgres"
  SPRING_DATASOURCE_PASSWORD: "password"
  SPRING_JPA_PROPERTIES_HIBERNATE_DEFAULT_SCHEMA: "catalog_schema"

service:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP

livenessProbe_enabled: true

readinessProbe_enabled: true