fullnameOverride: catalog

image:
  repository: e-commerce-es-catalog
  tag: latest
  pullPolicy: IfNotPresent

ports:
  - containerPort: 8080

env:
  SPRING_PROFILES_ACTIVE: "docker"
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5433/eCommerce
  SPRING_DATASOURCE_USERNAME: "postgres"
  SPRING_DATASOURCE_PASSWORD: "password"
  SPRING_JPA_PROPERTIES_HIBERNATE_DEFAULT_SCHEMA: "catalog_schema"

serviceAccount:
  create: false

autoscaling:
  enabled: false

configmap:
  enabled: false

service:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP

livenessProbe_enabled: true

readinessProbe_enabled: true

ingress:
  enabled: false