version: '2.1'

services:
  discovery:
    build: discovery
    mem_limit: 512m
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - ecommerce-networks


  gateway:
    build: gateway
    mem_limit: 512m
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery:8761/eureka/
    depends_on:
      - discovery
    networks:
      - ecommerce-networks

  postgres-db:
    image: postgres:16.0
    restart: always
    environment:
      POSTGRES_DB: eCommerce
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "password"
      TZ: America/Sao_Paulo
    ports:
      - "5433:5432"
    expose:
      - "5432"
    networks:
      - ecommerce-networks
    volumes:
      - pg-data:/var/lib/postgresql/data
    user: "postgres"  # Adiciona esta linha para rodar como usuário 'postgres'
    command: >
      bash -c "
        postgres -c 'shared_buffers=256MB' &
        sleep 5 &&
        psql -U postgres -d eCommerce -c 'CREATE SCHEMA IF NOT EXISTS catalog_schema;' &&
        psql -U postgres -d eCommerce -c 'CREATE SCHEMA IF NOT EXISTS price_schema;' &&
        psql -U postgres -d eCommerce -c 'CREATE SCHEMA IF NOT EXISTS inventory_schema;' &&
        wait
      "


  catalog:
    build: catalog
    mem_limit: 256m
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/eCommerce
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_PROPERTIES_HIBERNATE_DEFAULT_SCHEMA=catalog_schema
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery:8761/eureka/
    depends_on:
      - postgres-db
      - discovery
    networks:
      - ecommerce-networks

  price:
    build: price
    mem_limit: 256m
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/eCommerce
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_PROPERTIES_HIBERNATE_DEFAULT_SCHEMA=price_schema
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery:8761/eureka/
    depends_on:
      - discovery
      - postgres-db
    networks:
      - ecommerce-networks
    restart: always

  inventory:
    build: inventory
    mem_limit: 256m
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/eCommerce
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=passowrd
      - SPRING_JPA_PROPERTIES_HIBERNATE_DEFAULT_SCHEMA=inventory_schema
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery:8761/eureka/
    depends_on:
      - postgres-db
      - discovery
    networks:
      - ecommerce-networks


  message:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - ecommerce-networks

volumes:
  pg-data:
    driver: local

networks:
  ecommerce-networks:
    driver: bridge
