

services:

  postgres-db:
    image: postgres:16.0
    restart: always
    environment:
      POSTGRES_DB: eCommerce
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "password"
      TZ: America/Sao_Paulo
    ports:
      - "5433:5432"
    networks:
      - ecommerce-networks
    volumes:
      - pg-data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 10

  catalog:
    build: ./catalog
    mem_limit: 256m
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/eCommerce
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
    ports:
    - "8080:8080"
    networks:
      - ecommerce-networks
    depends_on:
   
      - postgres-db

  price:
    build: price
    mem_limit: 256m
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/eCommerce
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_PROPERTIES_HIBERNATE_DEFAULT_SCHEMA=price_schema
    ports:
    - "8081:8081"
    depends_on:
      - postgres-db
    networks:
      - ecommerce-networks

  inventory:
    build: inventory
    mem_limit: 256m
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/eCommerce
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_PROPERTIES_HIBERNATE_DEFAULT_SCHEMA=inventory_schema
    ports:
    - "8082:8082"
    depends_on:
      - postgres-db
    networks:
      - ecommerce-networks

  keycloak:
    image: quay.io/keycloak/keycloak
    ports:
      - "8090:8080"
    networks:
      - ecommerce-networks
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      DB_VENDOR: POSTGRES
      DB_ADDR: keycloak-db
      DB_PORT: 5432
      DB_DATABASE: keycloak
      DB_USER: postgres
      DB_SCHEMA: public
      DB_PASSWORD: password
    volumes:
      - ./auth/realm-export.json:/opt/keycloak/realm-export.json
      - ./keycloak-entrypoint.sh:/opt/keycloak/keycloak-entrypoint.sh
    entrypoint: ["/opt/keycloak/keycloak-entrypoint.sh"]
    depends_on:
      - keycloak-db

  keycloak-db:
    image: postgres:16.0
    restart: always
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      TZ: America/Sao_Paulo
    ports:
      - "5434:5432"
    expose:
      - "5432"
    networks:
      - ecommerce-networks
    volumes:
      - keycloak-pg-data:/var/lib/postgresql/data

  auth:
    build: auth
    mem_limit: 512m
    ports:
      - "9090:9090"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - keycloak
    networks:
      - ecommerce-networks

  message:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - ecommerce-networks



volumes:
  pg-data:
    driver: local
  keycloak-pg-data:
    driver: local

networks:
  ecommerce-networks:
    driver: bridge
