version: '2.1'

services:
  
  catalog:
    build: catalog
    mem_limit: 256m
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
  price:
    build: price
    mem_limit: 256m
    environment:
      - SPRING_PROFILES_ACTIVE=docker
  inventory:
    build: inventory
    mem_limit: 256m
    environment:
      - SPRING_PROFILES_ACTIVE=docker
 
  message:
     image: "rabbitmq:3-management"
     ports: 
       - "5672:5672"
       - "15672:15672"