
fullnameOverride: gateway

image:
  repository: localhost:5000/e-commerce-es-gateway
  tag: latest
  pullPolicy: IfNotPresent

ports:
  - containerPort: 8083

env:
  SPRING_PROFILES_ACTIVE: "docker"

livenessProbe_enabled: true
livenessProbe:
  httpGet:
    scheme: HTTPS
    port: 8083
readinessProbe_enabled: true
readinessProbe:
  httpGet:
    scheme: HTTPS
    port: 8083

serviceAccount:
  create: false

configmap:
  enabled: false

service:
  type: LoadBalancer
  ports:
    - port: 8083
      targetPort: 8383
      protocol: TCP

ingress:
  enabled: false

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
