server:
  port: 8084

spring:
  application:
    name: price
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres-db:5432/eCommerce
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    properties:
      hibernate:
        default_schema: price_schema
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql

  config:
    activate:
      on-profile: docker

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5

app:
  catalog-service:
    host: http://localhost:8081/catalog

spring.cloud.function.definition: consumeMessage

spring.cloud.stream:
  defaultBinder: rabbit
  default.contentType: application/json
  bindings.consumeMessage-in-0:
    destination: price
    group: pricesGroup

spring.cloud.stream.bindings.consumeMessage-in-0.consumer:
  maxAttempts: 3
  backOffInitialInterval: 500
  backOffMaxInterval: 1000
  backOffMultiplier: 2.0

spring.cloud.stream.rabbit.bindings.consumeMessage-in-0.consumer:
  autoBindDlq: true
  republishToDlq: true
  
  
spring.rabbitmq:
  host: ${MESSAGE_HOST:localhost}
  port: 5672
  username: guest
  password: guest

---
spring.config.activate.on-profile: docker

spring.rabbitmq:
  host: message

spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:postgresql://postgres-price:5432/price
  application:
    name: price

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/

app:
  catalog-service:
    host: http://catalog:8080/catalog