server:
  port: 8083

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: catalog
          uri: http://catalog:8080
          predicates:
            - Path=/catalog/**
        - id: inventory
          uri: http://inventory:8082
          predicates:
            - Path=/inventory/**
        - id: price
          uri: http://price:8081
          predicates:
            - Path=/price/**


logging:
  level:
    root: INFO
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: INFO
    org.springframework.cloud.gateway: TRACE

---

spring:
  config:
    activate:
      on-profile: docker

