spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes:
        - id: eureka-web-start
          uri: http://${app.eureka-server}:8761
          predicates:
            - Path=/eureka/web
          filters:
            - SetPath=/

        - id: eureka-web-other
          uri: http://${app.eureka-server}:8761
          predicates:
            - Path=/eureka/**

        - id: catalog
          uri: lb://catalog
          predicates:
            - Path=/catalog/**

        - id: inventory
          uri: lb://inventory
          predicates:
            - Path=/inventory/**

        - id: price
          uri: lb://price
          predicates:
            - Path=/price/**

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://discovery:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 5

app:
  eureka-server: discovery
