fullnameOverride: inventory

image:
  repository: e-commerce-es-inventory
  tag: latest
  pullPolicy: IfNotPresent

ports:
  - containerPort: 8082

env:
  SPRING_PROFILES_ACTIVE: "docker"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres-db:5432/eCommerce"
  SPRING_DATASOURCE_USERNAME: "postgres"
  SPRING_DATASOURCE_PASSWORD: "password"
  SPRING_JPA_PROPERTIES_HIBERNATE_DEFAULT_SCHEMA: "inventory_schema"

serviceAccount:
  create: false

configmap:
  enabled: false

service:
  type: LoadBalancer
  ports:
    - port: 8082
      targetPort: 8082
      protocol: TCP

ingress:
  enabled: false

livenessProbe_enabled: true

readinessProbe_enabled: true

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
