server:
  port: 8084

spring:
  application:
    name: auth

  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: app_client
            authorization-grant-type: authorization_code
            scope: openid
        provider:
          keycloak:
            issuer-uri: http://localhost:8090/realms/tees
            user-name-attribute: preferred_username
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8090/realms/tees/protocol/openid-connect/certs

---

server:
  port: 8084

spring:
  config:
    activate:
      on-profile: docker
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://keycloak:8080/realms/tees/protocol/openid-connect/certs
      client:
        registration:
          keycloak:
            client-id: app_client
            authorization-grant-type: authorization_code
            scope: openid
        provider:
          keycloak:
            issuer-uri: http://keycloak:8080/realms/tees
            user-name-attribute: preferred_username