# Configuração do PostgreSQL
postgres:
  env:
    POSTGRES_DB: "eCommerce"
    POSTGRES_USER: "postgres"
    POSTGRES_PASSWORD: "password"
  service:
    ports:
      - port: 5433
        targetPort: 5432

# Configuração do RabbitMQ
rabbitmq:
  env:
    RABBITMQ_DEFAULT_USER: "guest"
    RABBITMQ_DEFAULT_PASS: "guest"
  service:
    ports:
      - name: tcp-not-secure
        port: 5672
      - name: http-mgm-ui
        port: 15672

# Configurações do Catalog Service
catalog:
  env:
    POSTGRES_DB: "eCommerce"
    POSTGRES_USER: "postgres"
    POSTGRES_PASSWORD: "password"

# Configurações do Gateway Service
gateway:
  env:
    POSTGRES_DB: "eCommerce"
    POSTGRES_USER: "postgres"
    POSTGRES_PASSWORD: "password"

# Configurações do Inventory Service
inventory:
  env:
    POSTGRES_DB: "eCommerce"
    POSTGRES_USER: "postgres"
    POSTGRES_PASSWORD: "password"

# Configurações do Price Service
price:
  env:
    POSTGRES_DB: "eCommerce"
    POSTGRES_USER: "postgres"
    POSTGRES_PASSWORD: "password"

# Configuração do Auth Service
auth:
  env:
    SPRING_PROFILES_ACTIVE: "docker"
    SPRING_APPLICATION_NAME: "auth"
    
    # Configurações do OAuth2 e JWT para o Keycloak
    SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_CLIENT_ID: "app_client"
    SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_AUTHORIZATION_GRANT_TYPE: "authorization_code"
    SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_SCOPE: "openid"
    SPRING_SECURITY_OAUTH2_PROVIDER_KEYCLOAK_ISSUER_URI: "http://keycloak:8089/realms/tees"
    SPRING_SECURITY_OAUTH2_PROVIDER_KEYCLOAK_USER_NAME_ATTRIBUTE: "preferred_username"
    
    # JWT Resource Server
    SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: "http://keycloak:8089/realms/tees/protocol/openid-connect/certs"
  service:
  type: "LoadBalancer"  # Ou "ClusterIP", "NodePort", dependendo da necessidade
  ports:
    - port: 8084
      targetPort: 8084
      protocol: TCP

