# Configuração do PostgreSQL
postgres:
  env:
    POSTGRES_DB: "eCommerce"
    POSTGRES_USER: "postgres"
    POSTGRES_PASSWORD: "password"
  service:
    ports:
      - port: 5433
        targetPort: 5432

# Configuração do RabbitMQ
rabbitmq:
  env:
    RABBITMQ_DEFAULT_USER: "guest"
    RABBITMQ_DEFAULT_PASS: "guest"
  service:
    ports:
      - name: tcp-not-secure
        port: 5672
      - name: http-mgm-ui
        port: 15672

# Configurações do Catalog Service
catalog:
  env:
    POSTGRES_DB: "eCommerce"
    POSTGRES_USER: "postgres"
    POSTGRES_PASSWORD: "password"

# Configurações do Gateway Service
gateway:
  env:
    POSTGRES_DB: "eCommerce"
    POSTGRES_USER: "postgres"
    POSTGRES_PASSWORD: "password"

# Configurações do Inventory Service
inventory:
  env:
    POSTGRES_DB: "eCommerce"
    POSTGRES_USER: "postgres"
    POSTGRES_PASSWORD: "password"

# Configurações do Price Service
price:
  env:
    POSTGRES_DB: "eCommerce"
    POSTGRES_USER: "postgres"
    POSTGRES_PASSWORD: "password"


