# Definindo segredos para o ambiente de desenvolvimento
secrets:
  postgres-secrets:
    POSTGRES_DB: eCommerce
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: password

  rabbitmq-secrets:
    RABBITMQ_DEFAULT_USER: guest
    RABBITMQ_DEFAULT_PASS: guest

# Configuração do PostgreSQL
postgres:
  env:
    POSTGRES_DB: "eCommerce"
    POSTGRES_USER: "postgres"
    POSTGRES_PASSWORD: "password"
  service:
    ports:
      - port: 5433
        targetPort: 5432

# Configuração do RabbitMQ
rabbitmq:
  env:
    RABBITMQ_DEFAULT_USER: "guest"
    RABBITMQ_DEFAULT_PASS: "guest"
  service:
    ports:
      - name: tcp-not-secure
        port: 5672
      - name: http-mgm-ui
        port: 15672

# Configurações do Catalog Service
catalog:
  envFromSecretRefs:
    - postgres-secrets

# Configurações do Gateway Service
gateway:
  envFromSecretRefs:
    - postgres-secrets

# Configurações do Inventory Service
inventory:
  envFromSecretRefs:
    - postgres-secrets

# Configurações do Price Service
price:
  envFromSecretRefs:
    - postgres-secrets
