auth:
  fullnameOverride: auth

  image:
    repository: e-commerce-es-auth  # Certifique-se de usar o repositório correto da imagem de auth
    tag: latest
    pullPolicy: IfNotPresent

  ports:
    - containerPort: 8084

  env:
    SPRING_PROFILES_ACTIVE: "docker"
    SPRING_APPLICATION_NAME: "auth"
    
    # Configurações do OAuth2 e JWT para o Keycloak
    SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_CLIENT_ID: "app_client"
    SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_AUTHORIZATION_GRANT_TYPE: "authorization_code"
    SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_SCOPE: "openid"
    SPRING_SECURITY_OAUTH2_PROVIDER_KEYCLOAK_ISSUER_URI: "http://keycloak:8089/realms/tees"
    SPRING_SECURITY_OAUTH2_PROVIDER_KEYCLOAK_USER_NAME_ATTRIBUTE: "preferred_username"
    
    # JWT Resource Server
    SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: "http://keycloak:8089/realms/tees/protocol/openid-connect/certs"

  serviceAccount:
    create: false

  autoscaling:
    enabled: false

  configmap:
    enabled: false

  service:
    type: "LoadBalancer"  # Ou "ClusterIP", "NodePort", dependendo da necessidade
    ports:
      - port: 8084
        targetPort: 8084
        protocol: TCP

  livenessProbe_enabled: true

  readinessProbe_enabled: true

  ingress:
    enabled: false
