apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-initdb
data:
  init.sql: |
    CREATE SCHEMA IF NOT EXISTS catalog_schema;
    CREATE SCHEMA IF NOT EXISTS inventory_schema;
    CREATE SCHEMA IF NOT EXISTS price_schema;
